In [1]:
import torch
import numpy as np
from Zonotope import Zonotope
# from zonotopes import Zonotope as Z

In [2]:
a = torch.Tensor([1,2])
b = torch.Tensor([[1.,1],[1,2]])
c = Zonotope(a,b)


In [3]:
k = (c+c)

In [4]:
d = k.center.sum()

In [5]:
d.backward()

In [6]:
k.center.grad

tensor([1., 1.])

In [7]:
c.A.grad

In [8]:
c.A

tensor([[-0.7071,  0.7071],
        [-0.8944,  0.4472],
        [ 0.7071, -0.7071],
        [ 0.8944, -0.4472]], grad_fn=<CatBackward0>)

In [9]:
c.b

tensor([1.4142, 0.4472, 0.0000, 0.4472], grad_fn=<CatBackward0>)

In [13]:
c.b.unsqueeze(dim=-1).shape

torch.Size([4, 1])