In [16]:
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
#Define model
def model(u,x0,h):
    x0[0] += h*u[0]*np.cos(x0[2])
    x0[1] += h*u[0]*np.sin(x0[2])
    x0[2] += h*u[1]
    x0[2] = (x0[2] + np.pi)%(2*np.pi)-np.pi
    return x0

In [18]:
#Define objective function
def objective(u,x0,x_goal,h):
    J=0.
    u = u.reshape((-1,2))
    for i in u:
        J =np.linalg.norm(x_goal[0:-1]-x0[0:-1])
        x0 = model(i,x0,h)
    return J

#Define constraint function
def constraint_ineq(u,umin,umax):
    return np.concatenate([umax-u,u-umin])


In [19]:
#Define the necessary variables
x0 = np.zeros(3)
x_goal = np.asarray([10,10,0])
M = 20
u0 = np.zeros(M*2)
umin = -2.
umax = 2.
h = 0.1

#Define Contraints
constraints = [{'type':'ineq','fun':constraint_ineq, 'args': (umin,umax)}]


In [20]:
x0 = np.zeros(3)
u_ = 0
for i in range(20):
    print(x0,u_)
    result = minimize(objective, x0=u0, args=(x0,x_goal,h), constraints=constraints)
    u0[:-2] = result.x[2:]
    u_ = result.x[0:2]
    x0 = model(u_,x0,h)
    # u0 = np.zeros(M*2)
    # u0[:-2] = result.x[2:]

[0. 0. 0.] 0
[-0.67092702  1.90180661 -2.34078305] [ 3.57729640e-04 -7.46478528e-05]
[-0.76006533  0.61397033 -0.9372587 ] [ 0.00020407 -0.00028367]
[-5.28114425e+10  1.40060127e+09  1.81605853e+00] [-51326242.67689259 -63846755.88659242]
[-5.51157383e+10  2.77304268e+09 -8.77817424e-01] [-19190503.44516645 -34286280.6901637 ]
[-5.52010541e+10  2.70850753e+09 -1.14118669e+00] [-58457998.44366634 -12387291.35728212]
[ 3.71161926e+15 -2.28331247e+16 -1.32302274e+00] [3.90458873e+12 7.87006471e+12]
[ 3.72964182e+15 -2.27979549e+16  1.61740353e+00] [1.16943977e+13 1.51790943e+13]
[ 3.67003277e+15 -2.27222589e+16  2.93303226e+00] [1.81430699e+13 2.04312381e+13]
[ 3.66424685e+15 -2.27080331e+16  5.95949525e-01] [2.19226041e+13 2.25399466e+13]
[ 3.86393817e+15 -2.27537383e+16 -8.50022664e-01] [2.22509990e+13 2.10706911e+13]
[ 4.17844854e+15 -2.27959913e+16 -2.91560787e+00] [1.90613093e+13 1.63267586e+13]
[ 4.19742138e+15 -2.28051075e+16 -6.05497747e-01] [1.30126491e+13 9.29053134e+12]
[ 4.159